package ec.edu.utpl.adopcionmascotas.vista;

import ec.edu.utpl.adopcionmascotas.controlador.ControladorAdministracion;
import ec.edu.utpl.adopcionmascotas.controlador.ThreadSistema;
import ec.edu.utpl.adopcionmascotas.controlador.Utilitarios;
import ec.edu.utpl.adopcionmascotas.modelo.pojo.Auditoria;
import ec.edu.utpl.adopcionmascotas.modelo.pojo.Sesion;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * Interfaz Principal de Administracion de la aplicacion
 * 
 * @author Grupo 3 - Ingeniería de Software
 * @version 1.0
 */
public class Administracion extends javax.swing.JFrame {

    private ControladorAdministracion administracion;
    private Utilitarios util;
    private Sesion sesion;
    
    private DefaultTableModel modelo;
    private Integer codigo;
    private String cambio;
    private String subtitulo;

    public Administracion(Sesion sesion) {
        
        try {
            util = new Utilitarios();
            this.sesion = sesion;
            this.administracion = new ControladorAdministracion(sesion.getIdSesion());
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            initComponents();
            setLocationRelativeTo(null);
            setDatosUsuario();
            setIcon();
            //Thread reloj = new ThreadSistema(lblHora, true);
            //reloj.start();
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this.rootPane,"Imposible modificar el tema visual","Lookandfeel inválido.",javax.swing.JOptionPane.ERROR_MESSAGE);
        }   
    }


    private void setDatosUsuario(){
        
        lblUsuario.setText("[" + sesion.getUsuario() + "]");
        lblNombreUsuario.setText(sesion.getNombreUsuario());
        lblInicioSesion.setText(sesion.getFinicio());
        lblInfoSistema.setText(sesion.getSistema());
        lblFecha.setText(util.tiempoSistema("EEEE',' dd 'de' MMMMM 'de' yyyy"));   
    }
    
    private void setIcon(){
        
        String icon = "";
        if("MUJER".equals(sesion.getGenero())){
            icon = "/images/imgMujerSmall.png";
        } else {
            icon = "/images/imgHombreSmall.png";
        }
        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panSuperior = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        lblTituloPrincipal = new javax.swing.JLabel();
        lblIcono1 = new javax.swing.JLabel();
        panLateral = new javax.swing.JPanel();
        btnRoles = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnModulos = new javax.swing.JButton();
        btnFuncionalidades = new javax.swing.JButton();
        btnCatalogos = new javax.swing.JButton();
        btnAuditoria = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        panPrincipal = new javax.swing.JPanel();
        scrContenido = new javax.swing.JScrollPane();
        tblContenido = new javax.swing.JTable();
        lblTituloSeccion = new javax.swing.JLabel();
        lblNombreSeccion = new javax.swing.JLabel();
        lblTituloContenido = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cmbEmpresa = new javax.swing.JComboBox<>();
        panInfoSistema = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        lblInicioSesion = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblInfoSistema = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración del Sistema");
        setMinimumSize(new java.awt.Dimension(1400, 860));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panSuperior.setBackground(new java.awt.Color(41, 41, 41));
        panSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panSuperior.setMinimumSize(new java.awt.Dimension(1400, 45));
        panSuperior.setPreferredSize(new java.awt.Dimension(1400, 45));
        panSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcono.setForeground(new java.awt.Color(255, 255, 255));
        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panSuperior.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 5, 50, 50));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("[usuario]");
        panSuperior.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 300, 25));

        lblNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreUsuario.setText("Nombre Completo Usuario");
        panSuperior.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 300, 25));

        lblSubTitulo.setBackground(new java.awt.Color(255, 153, 51));
        lblSubTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSubTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTitulo.setText("Sistema");
        panSuperior.add(lblSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 400, 15));

        lblTituloPrincipal.setBackground(new java.awt.Color(255, 153, 51));
        lblTituloPrincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPrincipal.setText("Contabilidad UTPL");
        panSuperior.add(lblTituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 400, 25));

        lblIcono1.setForeground(new java.awt.Color(255, 255, 255));
        lblIcono1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgLogoUtpl.png"))); // NOI18N
        panSuperior.add(lblIcono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 50));

        getContentPane().add(panSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 0, 1155, 110));

        panLateral.setBackground(new java.awt.Color(255, 54, 54));
        panLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRoles.setText("ROLES");
        btnRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolesActionPerformed(evt);
            }
        });
        panLateral.add(btnRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 150, 40));

        btnUsuarios.setText("USUARIOS");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        panLateral.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, 40));

        btnModulos.setText("MODULOS");
        btnModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModulosActionPerformed(evt);
            }
        });
        panLateral.add(btnModulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 150, 40));

        btnFuncionalidades.setText("FUNCIONALIDAD");
        btnFuncionalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionalidadesActionPerformed(evt);
            }
        });
        panLateral.add(btnFuncionalidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 40));

        btnCatalogos.setText("CATALOGOS");
        btnCatalogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogosActionPerformed(evt);
            }
        });
        panLateral.add(btnCatalogos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 325, 150, 40));

        btnAuditoria.setText("AUDITORIA");
        btnAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuditoriaActionPerformed(evt);
            }
        });
        panLateral.add(btnAuditoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 375, 150, 40));

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panLateral.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 150, 40));

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        panLateral.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 150, 40));

        getContentPane().add(panLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 245, 670));

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContenidoMouseClicked(evt);
            }
        });
        scrContenido.setViewportView(tblContenido);

        panPrincipal.add(scrContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 1070, 310));

        lblTituloSeccion.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        panPrincipal.add(lblTituloSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 20));

        lblNombreSeccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panPrincipal.add(lblNombreSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 500, 30));

        lblTituloContenido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloContenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panPrincipal.add(lblTituloContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 760, 30));

        btnCrear.setText("Crear");
        btnCrear.setEnabled(false);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        panPrincipal.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 100, 40));

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panPrincipal.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, 100, 40));

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panPrincipal.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 550, 100, 40));

        panPrincipal.add(cmbEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 150, 160, -1));

        panInfoSistema.setBackground(new java.awt.Color(41, 41, 41));
        panInfoSistema.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("Inicio sesión:");
        panInfoSistema.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 20));

        lblInicioSesion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        panInfoSistema.add(lblInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 300, 20));

        lblHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHora.setText("00:00:00");
        panInfoSistema.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 80, 20));

        lblInfoSistema.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInfoSistema.setForeground(new java.awt.Color(255, 255, 255));
        panInfoSistema.add(lblInfoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 400, 20));

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panInfoSistema.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 260, 20));

        panPrincipal.add(panInfoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 610, 1155, 60));

        getContentPane().add(panPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        volver(sesion);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tblContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContenidoMouseClicked
        
        tblContenido.setColumnSelectionAllowed(true);
        tblContenido.setCellSelectionEnabled(false);
        int fila = tblContenido.getSelectedRow();
        if(fila != -1){
                lblTituloSeccion.setText(subtitulo);
                this.codigo = Integer.parseInt(tblContenido.getValueAt(fila, 0).toString());
                String dato = tblContenido.getValueAt(fila, 2).toString();
                lblNombreSeccion.setText(dato);
           enableBotones(true);
        }
    }//GEN-LAST:event_tblContenidoMouseClicked

    private void btnRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolesActionPerformed
        
        try {
            cambio = "ROL";
            cmbEmpresa.removeAllItems();
            lblTituloSeccion.setText(null);
            lblNombreSeccion.setText(null);
            subtitulo = "Rol";
            lblTituloContenido.setText("Roles del Sistema");
            administracion.fillTableRoles(tblContenido, modelo);
            cmbEmpresa.addItem("Todos los Roles");
            btnCrear.setEnabled(true);
            enableBotones(false);
        } catch (IOException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRolesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        try {
            cambio = "USU";
            cmbEmpresa.removeAllItems();
            lblTituloSeccion.setText(null);
            lblNombreSeccion.setText(null);
            subtitulo = "Usuario";
            lblTituloContenido.setText("Usuarios del Sistema");
            administracion.fillTableUsuarios(tblContenido, modelo);
            cmbEmpresa.addItem("Todos los Usuarios");
            btnCrear.setEnabled(true);
            enableBotones(false);
        } catch (IOException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModulosActionPerformed
        try {
            cambio = "MOD";
            cmbEmpresa.removeAllItems();
            lblTituloSeccion.setText(null);
            lblNombreSeccion.setText(null);
            subtitulo = "Módulo";
            lblTituloContenido.setText("Módulos del Sistema");
            administracion.fillTableModulos(tblContenido, modelo);
            cmbEmpresa.addItem("Todos los Modulos");
            btnCrear.setEnabled(true);
            enableBotones(false);
        } catch (IOException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModulosActionPerformed

    private void btnFuncionalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionalidadesActionPerformed
        try {
            cambio = "FUN";
            cmbEmpresa.removeAllItems();
            lblTituloSeccion.setText(null);
            lblNombreSeccion.setText(null);
            subtitulo = "Funcionalidad";
            lblTituloContenido.setText("Funcionalidades del Sistema");
            administracion.fillTableFuncionalidades(tblContenido, modelo);
            cmbEmpresa.addItem("Todas las Funcionalidades");
            btnCrear.setEnabled(true);
            enableBotones(false);
        } catch (IOException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFuncionalidadesActionPerformed

    private void btnCatalogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogosActionPerformed
        try {
            cambio = "CAT";
            cmbEmpresa.removeAllItems();
            lblTituloSeccion.setText(null);
            lblNombreSeccion.setText(null);
            subtitulo = "Catálogo";
            lblTituloContenido.setText("Catálogos del Sistema");
            administracion.fillTableCatalogos(tblContenido, modelo);
            cmbEmpresa.addItem("Todos los Catálogos");
            btnCrear.setEnabled(true);
            enableBotones(false);
        } catch (IOException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCatalogosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        codigo = null;
        cmbEmpresa.removeAllItems();
        lblTituloContenido.setText(null);
        lblTituloSeccion.setText(null);
        lblNombreSeccion.setText(null);
        cambio = null;
        btnCrear.setEnabled(false);
        enableBotones(false);
        modelo = new DefaultTableModel();
        tblContenido.setModel(modelo);

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        try {
            /*if("EMP".equals(cambio)) {
                GestionEmpresa empresa = new GestionEmpresa(sesion, null, "NUEVO");
                empresa.setVisible(true);
            } else if("ROL".equals(cambio)) {
                GestionRol rol = new GestionRol(sesion, null, "NUEVO");
                rol.setVisible(true);
            } else if("USU".equals(cambio)) {
                GestionUsuario usuario = new GestionUsuario(sesion, null, "NUEVO");
                usuario.setVisible(true);
            } else if("MOD".equals(cambio)) {
                GestionModulo modulo = new GestionModulo(sesion, null, "NUEVO");
                modulo.setVisible(true);
            } else if("FUN".equals(cambio)) {
                GestionFuncionalidad funcionalidad = new GestionFuncionalidad(sesion, null, "NUEVO");
                funcionalidad.setVisible(true);
            } else if("CAT".equals(cambio)) {
                GestionCatalogo catalogo = new GestionCatalogo(sesion, null, "NUEVO");
                catalogo.setVisible(true);
            }*/
            this.dispose(); 
        }catch(Exception ex) {
             Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       
        try {
            /*if("EMP".equals(cambio)) {
                GestionEmpresa empresa = new GestionEmpresa(sesion, codigo, "EDITAR");
                empresa.setVisible(true);
            } else if("ROL".equals(cambio)) {
                GestionRol rol = new GestionRol(sesion, codigo, "EDITAR");
                rol.setVisible(true);
            } else if("USU".equals(cambio)) {
                GestionUsuario usuario = new GestionUsuario(sesion, codigo, "EDITAR");
                usuario.setVisible(true);
            } else if("MOD".equals(cambio)) {
                GestionModulo modulo = new GestionModulo(sesion, codigo, "EDITAR");
                modulo.setVisible(true);
            } else if("FUN".equals(cambio)) {
                GestionFuncionalidad funcionalidad = new GestionFuncionalidad(sesion, codigo, "EDITAR");
                funcionalidad.setVisible(true);
            } else if("CAT".equals(cambio)) {
                GestionCatalogo catalogo = new GestionCatalogo(sesion, codigo, "EDITAR");
                catalogo.setVisible(true);
            }*/
            this.dispose();
        }catch(Exception ex) {
             Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
            
        try {
            /*if("EMP".equals(cambio)) {
                GestionEmpresa empresa = new GestionEmpresa(sesion, codigo, "ELIMINAR");
                empresa.setVisible(true);
            } else if("ROL".equals(cambio)) {
                GestionRol rol = new GestionRol(sesion, codigo, "ELIMINAR");
                rol.setVisible(true);
            } else if("USU".equals(cambio)) {
                GestionUsuario usuario = new GestionUsuario(sesion, codigo, "ELIMINAR");
                usuario.setVisible(true);
            } else if("MOD".equals(cambio)) {
                GestionModulo modulo = new GestionModulo(sesion, codigo, "ELIMINAR");
                modulo.setVisible(true);
            } else if("FUN".equals(cambio)) {
                GestionFuncionalidad funcionalidad = new GestionFuncionalidad(sesion, codigo, "ELIMINAR");
                funcionalidad.setVisible(true);
            } else if("CAT".equals(cambio)) {
                GestionCatalogo catalogo = new GestionCatalogo(sesion, codigo, "ELIMINAR");
                catalogo.setVisible(true);
            }*/
            this.dispose();
        }catch(Exception ex) {
             Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        administracion.salir(sesion);
    }//GEN-LAST:event_formWindowClosing

    private void btnAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuditoriaActionPerformed
        /*Auditoria auditoria = new Auditoria(sesion);
        auditoria.setVisible(true);*/
        this.dispose();
    }//GEN-LAST:event_btnAuditoriaActionPerformed

    private void enableBotones(Boolean enable){ 
        btnEditar.setEnabled(enable);
        btnEliminar.setEnabled(enable);   
    }
    
    private void volver(Sesion sesion){
        
        Inicio inicio = new Inicio();
        inicio.setIsLogged(true);
        inicio.setSesion(sesion);
        inicio.disableLogin();
        inicio.setVisible(true);
        this.dispose();      
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuditoria;
    private javax.swing.JButton btnCatalogos;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFuncionalidades;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModulos;
    private javax.swing.JButton btnRoles;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JComboBox<String> cmbEmpresa;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIcono1;
    private javax.swing.JLabel lblInfoSistema;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblInicioSesion;
    private javax.swing.JLabel lblNombreSeccion;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTituloContenido;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JLabel lblTituloSeccion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panInfoSistema;
    private javax.swing.JPanel panLateral;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panSuperior;
    private javax.swing.JScrollPane scrContenido;
    private javax.swing.JTable tblContenido;
    // End of variables declaration//GEN-END:variables
}
