package ec.edu.utpl.adopcionmascotas.vista;

import ec.edu.utpl.adopcionmascotas.controlador.ControladorAuditoria;
import ec.edu.utpl.adopcionmascotas.controlador.ThreadSistema;
import ec.edu.utpl.adopcionmascotas.controlador.Utilitarios;
import ec.edu.utpl.adopcionmascotas.modelo.pojo.Sesion;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * Interfaz Principal de Auditoria de la aplicacion
 * 
 * @author Cristian Espinoza
 * @version 2.0
 */
public class Auditoria extends javax.swing.JFrame {

    private ControladorAuditoria auditoria;
    private Utilitarios util;
    private Sesion sesion;
    
    private DefaultTableModel modelo;
    
    public Auditoria(Sesion sesion) {
        
        try {
            util = new Utilitarios();
            this.sesion = sesion;
            this.auditoria = new ControladorAuditoria(sesion.getIdSesion());
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            initComponents();
            setLocationRelativeTo(null);
            setDatosUsuario();
            setIcon();
            //Thread reloj = new ThreadSistema(lblHora, true);
            //reloj.start();
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this.rootPane,"Imposible modificar el tema visual","Lookandfeel inválido.",javax.swing.JOptionPane.ERROR_MESSAGE);
        }   
    }
    
    private void setDatosUsuario(){
        
        lblUsuario.setText("[" + sesion.getUsuario() + "]");
        lblNombreUsuario.setText(sesion.getNombreUsuario());
        lblInicioSesion.setText(sesion.getFinicio());
        lblInfoSistema.setText(sesion.getSistema());
        lblFecha.setText(util.tiempoSistema("EEEE',' dd 'de' MMMMM 'de' yyyy"));   
    }
    
    private void setIcon(){
        
        String icon = "";
        if("F".equals(sesion.getGenero())){
            icon = "/images/imgMujerSmall.png";
        } else {
            icon = "/images/imgHombreSmall.png";
        }
        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panSuperior = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblLogoUtpl = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        lblTituloPrincipal = new javax.swing.JLabel();
        panLateral = new javax.swing.JPanel();
        btnSesiones = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        panTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panPrincipal = new javax.swing.JPanel();
        lblTituloContenido = new javax.swing.JLabel();
        scrContenido = new javax.swing.JScrollPane();
        tblContenido = new javax.swing.JTable();
        panInfoSistema = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        lblInicioSesion = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblInfoSistema = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auditoría del Sistema");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panSuperior.setBackground(new java.awt.Color(41, 41, 41));
        panSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcono.setForeground(new java.awt.Color(255, 255, 255));
        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panSuperior.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 64, 80));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("[usuario]");
        panSuperior.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 300, 30));

        lblNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 204, 0));
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreUsuario.setText("Nombre Completo Usuario");
        panSuperior.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 300, 20));

        lblLogoUtpl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLogoUtpl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgLogoUtplGrande.png"))); // NOI18N
        panSuperior.add(lblLogoUtpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 64));

        lblSubTitulo.setBackground(new java.awt.Color(255, 153, 51));
        lblSubTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSubTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTitulo.setText("Sistema");
        panSuperior.add(lblSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 400, 20));

        lblTituloPrincipal.setBackground(new java.awt.Color(255, 153, 51));
        lblTituloPrincipal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPrincipal.setText("Adopcion de Mascotas");
        panSuperior.add(lblTituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 400, 30));

        getContentPane().add(panSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 100));

        panLateral.setBackground(new java.awt.Color(41, 41, 41));
        panLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSesiones.setText("SESIONES");
        btnSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionesActionPerformed(evt);
            }
        });
        panLateral.add(btnSesiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 100, 40));

        btnRegistro.setText("REGISTRO");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        panLateral.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 40));

        btnRegresar.setText("VOLVER");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panLateral.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 100, 40));

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        panLateral.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 100, 40));

        getContentPane().add(panLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 560));

        panTitulo.setBackground(new java.awt.Color(255, 54, 54));
        panTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitulo.setText("Registro de Auditoria");
        panTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 5, 360, 30));

        getContentPane().add(panTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 40));

        panPrincipal.setBackground(new java.awt.Color(41, 41, 41));
        panPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloContenido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloContenido.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloContenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panPrincipal.add(lblTituloContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 760, 30));

        tblContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContenidoMouseClicked(evt);
            }
        });
        scrContenido.setViewportView(tblContenido);

        panPrincipal.add(scrContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 760, 380));

        getContentPane().add(panPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 800, 500));

        panInfoSistema.setBackground(new java.awt.Color(41, 41, 41));
        panInfoSistema.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("Inicio sesión:");
        panInfoSistema.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        lblInicioSesion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        panInfoSistema.add(lblInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 300, 20));

        lblHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHora.setText("00:00:00");
        panInfoSistema.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 80, 20));

        lblInfoSistema.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInfoSistema.setForeground(new java.awt.Color(255, 255, 255));
        panInfoSistema.add(lblInfoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 400, 20));

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panInfoSistema.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 260, 20));

        getContentPane().add(panInfoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 800, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        auditoria.salir(sesion);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        auditoria.salir(sesion);
    }//GEN-LAST:event_formWindowClosing

    private void tblContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContenidoMouseClicked

    }//GEN-LAST:event_tblContenidoMouseClicked

    private void btnSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionesActionPerformed
        try {
            lblTituloContenido.setText("Registro de Inicio de Sesión en el Sistema");
            auditoria.fillDataSesiones(tblContenido, modelo);
        } catch (IOException ex) {
            Logger.getLogger(Auditoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSesionesActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        try {
            lblTituloContenido.setText("Registro de Acciones en el Sistema");
            auditoria.fillDatosAuditoria(tblContenido, modelo);
        } catch (IOException ex) {
            Logger.getLogger(Auditoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Administracion administracion = new Administracion(sesion);
        administracion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSesiones;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblInfoSistema;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblInicioSesion;
    private javax.swing.JLabel lblLogoUtpl;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloContenido;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panInfoSistema;
    private javax.swing.JPanel panLateral;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panSuperior;
    private javax.swing.JPanel panTitulo;
    private javax.swing.JScrollPane scrContenido;
    private javax.swing.JTable tblContenido;
    // End of variables declaration//GEN-END:variables
}
