package ec.edu.utpl.adopcionmascotas.vista;

import ec.edu.utpl.adopcionmascotas.controlador.Reportes;
import ec.edu.utpl.adopcionmascotas.modelo.pojo.Catalogo;
import ec.edu.utpl.adopcionmascotas.modelo.pojo.Sesion;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.ColorUIResource;


/**
 * Interfaz de Generacion de Reportes
 * 
 * @author Grupo 3 - Ingeniería de Software
 * @version 1.0
 */
public class GeneracionReportes extends javax.swing.JFrame {

    private Sesion sesion;
    private JFrame contenedorReporte;
    /**
     * Creates new form GeneracionReportes
     */
    public GeneracionReportes(Sesion sesion) {
        
        try {
            this.sesion = sesion;           
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            javax.swing.UIManager.put("OptionPane.background",new ColorUIResource(41,41,41));
            javax.swing.UIManager.put("Panel.background",new ColorUIResource(41,41,41));
            javax.swing.UIManager.put("OptionPane.messageForeground",new ColorUIResource(255,255,255));
            javax.swing.UIManager.put("Panel.background",new ColorUIResource(41,41,41));
            
            initComponents();
            this.setLocationRelativeTo(null);
            loadCatalogo();
        }catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e){
            javax.swing.JOptionPane.showMessageDialog(this.rootPane,"Imposible modificar el tema visual","Lookandfeel inválido.",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panReporte = new javax.swing.JPanel();
        lblRerporte = new javax.swing.JLabel();
        cmbReporte = new javax.swing.JComboBox<>();
        cmbUsuarios = new javax.swing.JComboBox<>();
        lblUusario = new javax.swing.JLabel();
        panencabezadoRep = new javax.swing.JPanel();
        lblIconoUtpl = new javax.swing.JLabel();
        lblTituloRep = new javax.swing.JLabel();
        lblTituloReporte = new javax.swing.JLabel();
        panTituloRep = new javax.swing.JPanel();
        lblSubtituloReporte = new javax.swing.JLabel();
        panInferiorRep = new javax.swing.JPanel();
        btnGenerarRep = new javax.swing.JButton();
        btnCancelarRep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperar contraseña");
        setMinimumSize(new java.awt.Dimension(500, 375));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 355));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panReporte.setBackground(new java.awt.Color(41, 41, 41));
        panReporte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panReporte.setMinimumSize(new java.awt.Dimension(500, 460));
        panReporte.setPreferredSize(new java.awt.Dimension(500, 460));
        panReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRerporte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRerporte.setForeground(new java.awt.Color(255, 255, 255));
        lblRerporte.setText("Reporte:");
        panReporte.add(lblRerporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 55, 90, 30));

        cmbReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ReporteGeneralMascotas", "ReporteAdopciones", "ReporteMascotasUsuario", "ReporteAdopcionesUsuario" }));
        cmbReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbReporteActionPerformed(evt);
            }
        });
        panReporte.add(cmbReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 55, 270, 30));

        panReporte.add(cmbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 270, 30));

        lblUusario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUusario.setForeground(new java.awt.Color(255, 255, 255));
        lblUusario.setText("Usuario:");
        panReporte.add(lblUusario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 90, 30));

        getContentPane().add(panReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 500, 185));

        panencabezadoRep.setBackground(new java.awt.Color(41, 41, 41));
        panencabezadoRep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoUtpl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgLogoPequeño.png"))); // NOI18N
        panencabezadoRep.add(lblIconoUtpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 15, 94, 50));

        lblTituloRep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloRep.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRep.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloRep.setText("Sistema");
        panencabezadoRep.add(lblTituloRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 15, 300, 20));

        lblTituloReporte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloReporte.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloReporte.setText("Adopción de Mascotas");
        panencabezadoRep.add(lblTituloReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 35, 300, 30));

        getContentPane().add(panencabezadoRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 80));
        panencabezadoRep.getAccessibleContext().setAccessibleParent(this);

        panTituloRep.setBackground(new java.awt.Color(255, 54, 54));
        panTituloRep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSubtituloReporte.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblSubtituloReporte.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtituloReporte.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtituloReporte.setText("Generación de Reportes");
        lblSubtituloReporte.setAlignmentX(0.5F);
        panTituloRep.add(lblSubtituloReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 390, -1));

        getContentPane().add(panTituloRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 500, 40));

        panInferiorRep.setBackground(new java.awt.Color(255, 54, 54));
        panInferiorRep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerarRep.setText("Generar");
        btnGenerarRep.setToolTipText("Recuperar la Contraseña");
        btnGenerarRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRepActionPerformed(evt);
            }
        });
        panInferiorRep.add(btnGenerarRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 30));

        btnCancelarRep.setText("Volver");
        btnCancelarRep.setToolTipText("Volver al Login");
        btnCancelarRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRepActionPerformed(evt);
            }
        });
        panInferiorRep.add(btnCancelarRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 100, 30));

        getContentPane().add(panInferiorRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 305, 500, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRepActionPerformed
        
        String nombrereporte = cmbReporte.getSelectedItem().toString();
        if(nombrereporte != null && !nombrereporte.trim().isEmpty()) {
            Reportes reporte = new Reportes();
            if("ReporteGeneralMascotas".equals(nombrereporte) || "ReporteAdopciones".equals(nombrereporte)){
                Map<String, Object> parametros = new HashMap<>();
                parametros.put("USUARIO", sesion.getUsuario());
                reporte.setParametros(parametros);
                reporte.generarReporte(contenedorReporte, nombrereporte, true);
                btnGenerarRep.setEnabled(true);
            }else if("ReporteMascotasUsuario".equals(nombrereporte) || "ReporteAdopcionesUsuario".equals(nombrereporte)){
                
                String nombreusuario = cmbUsuarios.getSelectedItem().toString();
                if(nombreusuario != null && !nombreusuario.trim().isEmpty()) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("USUARIOMASCOTA", nombreusuario);
                    parametros.put("USUARIO", sesion.getUsuario());
                    
                    reporte.setParametros(parametros);
                    reporte.generarReporte(contenedorReporte, nombrereporte, true);
                    btnGenerarRep.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this.rootPane,"Debe elegir el usuario para el reporte.","Reportes",JOptionPane.WARNING_MESSAGE);
                } 
            }  
        } else {
            JOptionPane.showMessageDialog(this.rootPane,"Debe elegir el reporte a generar.","Reportes",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerarRepActionPerformed

    private void btnCancelarRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRepActionPerformed

        volver(sesion);  
    }//GEN-LAST:event_btnCancelarRepActionPerformed

    private void cmbReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbReporteActionPerformed
        
        String rep = cmbReporte.getSelectedItem().toString();
        if("ReporteMascotasUsuario".equals(rep) || "ReporteAdopcionesUsuario".equals(rep)){
            cmbUsuarios.setEnabled(true);
            cmbUsuarios.setSelectedIndex(0);
        } else {
            cmbUsuarios.setSelectedIndex(0);
            cmbUsuarios.setEnabled(false);
        }
    }//GEN-LAST:event_cmbReporteActionPerformed

    private void volver(Sesion sesion){
        
        Administracion administracion = new Administracion(sesion);
        administracion.setVisible(true);
        contenedorReporte.dispose();
        this.dispose();      
    }
    
    private void loadCatalogo(){
        
        this.contenedorReporte = new JFrame("Visor de Reportes");
        this.contenedorReporte .setMinimumSize(new java.awt.Dimension(1200, 800));
            
        Catalogo catalogo = new Catalogo();    
        catalogo.setComboUsuarios(cmbUsuarios);
        cmbUsuarios.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarRep;
    private javax.swing.JButton btnGenerarRep;
    private javax.swing.JComboBox<String> cmbReporte;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel lblIconoUtpl;
    private javax.swing.JLabel lblRerporte;
    private javax.swing.JLabel lblSubtituloReporte;
    private javax.swing.JLabel lblTituloRep;
    private javax.swing.JLabel lblTituloReporte;
    private javax.swing.JLabel lblUusario;
    private javax.swing.JPanel panInferiorRep;
    private javax.swing.JPanel panReporte;
    private javax.swing.JPanel panTituloRep;
    private javax.swing.JPanel panencabezadoRep;
    // End of variables declaration//GEN-END:variables
}
