package ec.edu.utpl.adopcionmascotas.vista;

import ec.edu.utpl.adopcionmascotas.controlador.ThreadSistema;
import ec.edu.utpl.adopcionmascotas.controlador.Utilitarios;
import ec.edu.utpl.adopcionmascotas.modelo.pojo.Mascota;
import ec.edu.utpl.adopcionmascotas.modelo.pojo.Sesion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.plaf.ColorUIResource;

/**
 * Interfaz de Inicio de la aplicacion
 * 
 * @author Grupo 3 - Ingeniería de Software
 * @version 1.0
 */
public class Inicio extends javax.swing.JFrame {

    private Sesion sesion;
    private Mascota mascota;
    private Utilitarios util;
    private Inicio ini;
    private boolean isLogged = false;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        
        try {
            this.util = new Utilitarios();
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            javax.swing.UIManager.put("OptionPane.background",new ColorUIResource(41,41,41));
            javax.swing.UIManager.put("Panel.background",new ColorUIResource(41,41,41));
            javax.swing.UIManager.put("OptionPane.messageForeground",new ColorUIResource(255,255,255));
            initComponents(); 
            setLocationRelativeTo(null);
            ini = this;        
            Thread reloj = new ThreadSistema(true, "HH:mm:ss", "EEEE',' dd 'de' MMMMM 'de' yyyy", lblHora, lblFecha, lblFotoPortadaA, lblFotoPortadaB, lblFotoPortadaC);
            reloj.start();
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this.rootPane,"Imposible modificar el tema visual","Lookandfeel inválido.",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        panInicioLateral = new javax.swing.JPanel();
        lblLogoPrincipal = new javax.swing.JLabel();
        btnVerMascotas = new javax.swing.JButton();
        btnPublicarMascota = new javax.swing.JButton();
        btnMisMascotas = new javax.swing.JButton();
        btnMisAdopciones = new javax.swing.JButton();
        btnGestionarUsuario = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        panInicioSuperior = new javax.swing.JPanel();
        lblInicioPortada = new javax.swing.JLabel();
        lblInicioSubtitulo = new javax.swing.JLabel();
        lblInicioTitulo = new javax.swing.JLabel();
        btnInicioLogin = new javax.swing.JButton();
        btnInicioRegistrar = new javax.swing.JButton();
        btnInicioSalir = new javax.swing.JButton();
        lblInicioAvatar = new javax.swing.JLabel();
        lblInicioBienvenida = new javax.swing.JLabel();
        lblInicioNombre = new javax.swing.JLabel();
        panInicioInferior = new javax.swing.JPanel();
        lblInicioUniversidad = new javax.swing.JLabel();
        lblInicioAutores = new javax.swing.JLabel();
        lblIncioUtpl = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblInicioSesion = new javax.swing.JLabel();
        lblInfoSistema = new javax.swing.JLabel();
        panInicioIntro = new javax.swing.JPanel();
        lblInicioTituloIntro = new javax.swing.JLabel();
        lblFotoPortadaA = new javax.swing.JLabel();
        lblFotoPortadaB = new javax.swing.JLabel();
        lblFotoPortadaC = new javax.swing.JLabel();
        scrInicioIntro = new javax.swing.JScrollPane();
        txpInicioIntro = new javax.swing.JTextPane();
        scrInicioMascotas = new javax.swing.JScrollPane();
        panInicioListadoMascotas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panInicioLateral.setBackground(new java.awt.Color(255, 54, 54));
        panInicioLateral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panInicioLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgLogoPrincipal.png"))); // NOI18N
        panInicioLateral.add(lblLogoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 245, 140));

        btnVerMascotas.setText("Ver mascotas");
        btnVerMascotas.setToolTipText("Ver las mascotas disponibles.");
        btnVerMascotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMascotasActionPerformed(evt);
            }
        });
        panInicioLateral.add(btnVerMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 365, 185, 60));

        btnPublicarMascota.setText("Publicar mascota");
        btnPublicarMascota.setToolTipText("Publicar una mascota.");
        btnPublicarMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPublicarMascota.setOpaque(false);
        btnPublicarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicarMascotaActionPerformed(evt);
            }
        });
        panInicioLateral.add(btnPublicarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 485, 185, 60));

        btnMisMascotas.setText("Mis mascotas");
        btnMisMascotas.setToolTipText("Ver mis mascotas publicadas.");
        btnMisMascotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMisMascotas.setOpaque(false);
        btnMisMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisMascotasActionPerformed(evt);
            }
        });
        panInicioLateral.add(btnMisMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 605, 185, 60));

        btnMisAdopciones.setText("Mis adopciones");
        btnMisAdopciones.setToolTipText("Ver mis mascotas adoptadas.");
        btnMisAdopciones.setBorder(null);
        btnMisAdopciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMisAdopciones.setOpaque(false);
        btnMisAdopciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisAdopcionesActionPerformed(evt);
            }
        });
        panInicioLateral.add(btnMisAdopciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 725, 185, 60));

        btnGestionarUsuario.setText("Gestionar usuario");
        btnGestionarUsuario.setToolTipText("Gestionar mi usuario.");
        btnGestionarUsuario.setBorder(null);
        btnGestionarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionarUsuario.setOpaque(false);
        btnGestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarUsuarioActionPerformed(evt);
            }
        });
        panInicioLateral.add(btnGestionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 845, 185, 60));

        lblHora.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("00:00:00");
        panInicioLateral.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 970, 245, 30));

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panInicioLateral.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1000, 245, 20));

        getContentPane().add(panInicioLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 245, 1040));

        panInicioSuperior.setBackground(new java.awt.Color(41, 41, 41));
        panInicioSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panInicioSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicioPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgFotoPortada.png"))); // NOI18N
        panInicioSuperior.add(lblInicioPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 417, 130));

        lblInicioSubtitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblInicioSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblInicioSubtitulo.setText("plataforma");
        panInicioSuperior.add(lblInicioSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 200, 30));

        lblInicioTitulo.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        lblInicioTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblInicioTitulo.setText("adopción de mascotas");
        panInicioSuperior.add(lblInicioTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 800, 120));

        btnInicioLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnLogin.png"))); // NOI18N
        btnInicioLogin.setToolTipText("Login de Usuario");
        btnInicioLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicioLogin.setOpaque(false);
        btnInicioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioLoginActionPerformed(evt);
            }
        });
        panInicioSuperior.add(btnInicioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 90, 50, 50));

        btnInicioRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnCrear.png"))); // NOI18N
        btnInicioRegistrar.setToolTipText("Crear Usuario Nuevo");
        btnInicioRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicioRegistrar.setOpaque(false);
        btnInicioRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioRegistrarActionPerformed(evt);
            }
        });
        panInicioSuperior.add(btnInicioRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 90, 50, 50));

        btnInicioSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnSalir.png"))); // NOI18N
        btnInicioSalir.setToolTipText("Salir de la Aplicación");
        btnInicioSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicioSalir.setOpaque(false);
        btnInicioSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSalirActionPerformed(evt);
            }
        });
        panInicioSuperior.add(btnInicioSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1465, 90, 50, 50));
        panInicioSuperior.add(lblInicioAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 15, 100, 125));

        lblInicioBienvenida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInicioBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lblInicioBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panInicioSuperior.add(lblInicioBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 20, 180, 20));

        lblInicioNombre.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lblInicioNombre.setForeground(new java.awt.Color(255, 204, 0));
        lblInicioNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panInicioSuperior.add(lblInicioNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 40, 370, 20));

        getContentPane().add(panInicioSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 0, 1675, 150));

        panInicioInferior.setBackground(new java.awt.Color(41, 41, 41));
        panInicioInferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panInicioInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicioUniversidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInicioUniversidad.setForeground(new java.awt.Color(255, 204, 0));
        lblInicioUniversidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInicioUniversidad.setText("Universidad Técnica Pasticular de Loja");
        panInicioInferior.add(lblInicioUniversidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 400, 20));

        lblInicioAutores.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblInicioAutores.setForeground(new java.awt.Color(255, 255, 255));
        lblInicioAutores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInicioAutores.setText("[ ESPINOZA - CONTRERAS - GÓMEZ - CEDEÑO - REA ]");
        panInicioInferior.add(lblInicioAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, 400, 20));

        lblIncioUtpl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgLogoUtplGrande.png"))); // NOI18N
        panInicioInferior.add(lblIncioUtpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1454, 10, 160, 64));

        lblInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panInicioInferior.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 20));

        lblInicioSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInicioSesion.setForeground(new java.awt.Color(255, 204, 0));
        lblInicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panInicioInferior.add(lblInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 500, 20));

        lblInfoSistema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInfoSistema.setForeground(new java.awt.Color(255, 204, 0));
        lblInfoSistema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panInicioInferior.add(lblInfoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 500, 20));

        getContentPane().add(panInicioInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 960, 1675, 80));

        panInicioIntro.setBackground(new java.awt.Color(255, 255, 255));
        panInicioIntro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panInicioIntro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicioTituloIntro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblInicioTituloIntro.setForeground(new java.awt.Color(255, 54, 54));
        lblInicioTituloIntro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInicioTituloIntro.setText("Adopta: ganamos todos !");
        lblInicioTituloIntro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panInicioIntro.add(lblInicioTituloIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 650, 30));

        lblFotoPortadaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgFotoGaleria4.png"))); // NOI18N
        lblFotoPortadaA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panInicioIntro.add(lblFotoPortadaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 260, 140));

        lblFotoPortadaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgFotoGaleria8.png"))); // NOI18N
        lblFotoPortadaB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panInicioIntro.add(lblFotoPortadaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 260, 140));

        lblFotoPortadaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgFotoGaleria12.png"))); // NOI18N
        lblFotoPortadaC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panInicioIntro.add(lblFotoPortadaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 260, 140));

        scrInicioIntro.setBorder(null);
        scrInicioIntro.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrInicioIntro.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrInicioIntro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txpInicioIntro.setEditable(false);
        txpInicioIntro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txpInicioIntro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txpInicioIntro.setText("A través de la historia, las mascotas han sido grandes compañeras de la vida de las personas, compartiendo alegrías, pero también ayudando a superar momentos difíciles.\n\nAdoptar es un gran paso. Hay muchos aspectos que debes considerar previamente, desde elegir el tipo de mascota más adecuada para tu estilo de vida, hasta decidir dónde o con quién adoptar. Por eso queremos ayudarte para que ésta sea una de las mejores experiencias en tu vida y la de tu próximo amigo de cuatro patas.");
        txpInicioIntro.setAutoscrolls(false);
        txpInicioIntro.setCaretColor(new java.awt.Color(255, 255, 255));
        scrInicioIntro.setViewportView(txpInicioIntro);

        panInicioIntro.add(scrInicioIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 650, 100));

        getContentPane().add(panInicioIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 165, 1645, 160));

        scrInicioMascotas.setBackground(new java.awt.Color(255, 255, 255));

        panInicioListadoMascotas.setBackground(new java.awt.Color(255, 255, 255));
        panInicioListadoMascotas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        scrInicioMascotas.setViewportView(panInicioListadoMascotas);

        getContentPane().add(scrInicioMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 1640, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMascotasActionPerformed
        
        panInicioListadoMascotas.removeAll();
        panInicioListadoMascotas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        setTituloMascotas(panInicioListadoMascotas, "Conoce nuestras mascotas...", "Puedes ver todas las mascotas disponibles para adopción, las cuales tienen todas sus vacunas y estan listas para ir contigo:");
        
        Integer reg = 1;
        Integer posX = 10;
        Integer posY = 68;
        Integer id = sesion != null ? sesion.getIdSesion() : null;
        mascota = new Mascota(id);
        List<Mascota> listadomascotas = mascota.getListadoMascota(id, "D", null, 1);
        if(listadomascotas.isEmpty()){
            scrInicioMascotas.updateUI();
        }
        for(Mascota mas : listadomascotas){
            if(reg % 2 == 0) {
                posX = 815;
            } else {
                posX = 10;
            }
            crearPanelMascota(mas, false, posX, posY);
            if(reg >1 && reg % 2 == 0){
                    posY = posY + 135; 
            }
            reg++;
        }
    }//GEN-LAST:event_btnVerMascotasActionPerformed

    private void setTituloMascotas(JPanel panel, String titulo, String subtitulo) {
         
        JLabel titulomascotaSec = new JLabel();
        titulomascotaSec.setFont(new java.awt.Font("Tahoma", 1, 24));
        titulomascotaSec.setForeground(new java.awt.Color(255, 54, 54));
        titulomascotaSec.setText(titulo);
        panel.add(titulomascotaSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 5, 690, 30));
        panel.repaint();
        JLabel subtitulomascotaSec = new JLabel();
        subtitulomascotaSec.setFont(new java.awt.Font("Tahoma", 0, 12));
        subtitulomascotaSec.setText(subtitulo);
        panel.add(subtitulomascotaSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 690, 20));
    }
    
    private void crearPanelMascota(Mascota mascota, boolean adopcion, Integer x, Integer y){
        
        try {
            JPanel panMascota = new JPanel();
            panMascota.setBackground(new java.awt.Color(41, 41, 41));
            panMascota.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            panMascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            
            JLabel fotoMascota = new JLabel();
            fotoMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgMascota01.png")));
            panMascota.add(fotoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 100, 100));
            
            JLabel nombreMascota = new JLabel();
            nombreMascota.setFont(new java.awt.Font("Tahoma", 1, 24));
            nombreMascota.setForeground(new java.awt.Color(255, 54, 54));
            nombreMascota.setText(mascota.getNombremascota());
            panMascota.add(nombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 15, 550, 30));
            
            JLabel fechaMascota = new JLabel();
            fechaMascota.setFont(new java.awt.Font("Tahoma", 0, 14));
            fechaMascota.setText("Publicación: " + mascota.getFpublicacion());
            fechaMascota.setForeground(new java.awt.Color(255, 255, 255));
            panMascota.add(fechaMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 55, 220, 20));
            
            JLabel ciudadMascota = new JLabel();
            ciudadMascota.setFont(new java.awt.Font("Tahoma", 0, 14));
            ciudadMascota.setText("Lugar: " + mascota.getProvincia() + ", " + mascota.getCiudad());
            ciudadMascota.setForeground(new java.awt.Color(255, 255, 255));
            panMascota.add(ciudadMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 75, 220, 20));
            
            JLabel edadMascota = new JLabel();
            edadMascota.setFont(new java.awt.Font("Tahoma", 0, 14));
            edadMascota.setText("Edad: " + mascota.getEdad() + " " + mascota.getUnidadedad());
            edadMascota.setForeground(new java.awt.Color(255, 255, 255));
            panMascota.add(edadMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 95, 220, 20));
            
            if(adopcion){
                JLabel usuarioAdoopcion = new JLabel();
                usuarioAdoopcion.setFont(new java.awt.Font("Tahoma", 1, 14));
                if(mascota.getUsuarioadopcion()!=null && !"".equals(mascota.getUsuarioadopcion())){
                    usuarioAdoopcion.setText("Adoptado: " + mascota.getNombreusuarioadopcion());
                } else {
                    usuarioAdoopcion.setText("Pendiente de Adopción");
                }
                usuarioAdoopcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                usuarioAdoopcion.setForeground(new java.awt.Color(255, 255, 255));
                panMascota.add(usuarioAdoopcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 15, 380, 30)); 
            }
            JButton btnVerMascota = new JButton();
            btnVerMascota.setOpaque(false);
            btnVerMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnVer.png")));
            btnVerMascota.setToolTipText("Ver la mascota.");
            btnVerMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnVerMascota.setEnabled(isLogged);
            
            btnVerMascota.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if(adopcion) {
                        if(mascota.getUsuarioadopcion()!=null && !"".equals(mascota.getUsuarioadopcion())){
                            GestionMascota gestionMascota = new GestionMascota(sesion, mascota, "CONSULTAR");
                            gestionMascota.setVisible(true);
                        } else {
                            GestionMascota gestionMascota = new GestionMascota(sesion, mascota, "EDITAR");
                            gestionMascota.setVisible(true);
                        }
                    } else {
                        AdopcionMascota adopcion = new AdopcionMascota(sesion, mascota);
                        adopcion.setAlwaysOnTop(true);
                        adopcion.setVisible(true);
                    }
                    
                    ini.dispose();
                }
            });
            
            panMascota.add(btnVerMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 55, 60, 60));
            
            JScrollPane scrObservaciones = new JScrollPane();
            scrObservaciones.setBorder(null);
            scrObservaciones.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            scrObservaciones.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
            scrObservaciones.setFont(new java.awt.Font("Tahoma", 0, 12));
                        
            JTextPane observaciones = new JTextPane();
            observaciones.setEditable(false);
            observaciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            observaciones.setFont(new java.awt.Font("Tahoma", 0, 12));
            observaciones.setText(mascota.getDescripcion());
            observaciones.setAutoscrolls(false);
            observaciones.setBackground(new java.awt.Color(41, 41, 41));
            observaciones.setForeground(new java.awt.Color(255, 204, 0));
            scrObservaciones.setViewportView(observaciones);
            panMascota.add(observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 55, 340, 60));
            
            panInicioListadoMascotas.add(panMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, 800, 130));
            panInicioListadoMascotas.updateUI();
        } catch (Exception ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnInicioSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSalirActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_btnInicioSalirActionPerformed

    private void btnInicioRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioRegistrarActionPerformed
        
        GestionUsuario gestionUsuario = new GestionUsuario(sesion, null, "NUEVO");
        gestionUsuario.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnInicioRegistrarActionPerformed

    private void btnInicioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioLoginActionPerformed
        
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioLoginActionPerformed

    private void btnMisAdopcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisAdopcionesActionPerformed
        
        if(isLogged){
            panInicioListadoMascotas.removeAll();
            panInicioListadoMascotas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            setTituloMascotas(panInicioListadoMascotas, "Estas son tus adopciones...", "Puedes ver todas las mascotas adoptadas por tí:");
            Integer reg = 1;
            Integer posX = 10;
            Integer posY = 68;
            Integer id = sesion != null ? sesion.getIdSesion() : null;
            mascota = new Mascota(id);
            List<Mascota> listadomascotas = mascota.getListadoMascota(id, "A", sesion.getUsuario(), 2);
            if(listadomascotas.isEmpty()){
                scrInicioMascotas.updateUI();
            }
            for(Mascota mas : listadomascotas){
                if(reg % 2 == 0) {
                    posX = 815;
                } else {
                    posX = 10;
                }
                crearPanelMascota(mas, true, posX, posY);
                if(reg >1 && reg % 2 == 0){
                        posY = posY + 135; 
                }
                reg++;
            }          
        } else {
            JOptionPane.showMessageDialog(this.rootPane,"Debe ingresar al sistema para visualizar sus adopciones.","Historial de Adopciones",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnMisAdopcionesActionPerformed

    private void btnPublicarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicarMascotaActionPerformed
        
        if(isLogged){
            mascota = null;
            GestionMascota gestionMascota = new GestionMascota(sesion, mascota, "PUBLICAR");
            gestionMascota.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this.rootPane,"Debe ingresar al sistema para publicar una mascota.","Adopciones",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPublicarMascotaActionPerformed

    private void btnMisMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisMascotasActionPerformed
        
        if(isLogged){
            panInicioListadoMascotas.removeAll();
            panInicioListadoMascotas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            setTituloMascotas(panInicioListadoMascotas, "Estas son tus mascotas publicadas...", "Puedes ver todas las mascotas publicadas por tí y que están en busca de un hogar:");
        
            Integer reg = 1;
            Integer posX = 10;
            Integer posY = 68;
            Integer id = sesion != null ? sesion.getIdSesion() : null;
            mascota = new Mascota(id);
            List<Mascota> listadomascotas = mascota.getListadoMascota(id, null, sesion.getUsuario(), 3);
            if(listadomascotas.isEmpty()){
                scrInicioMascotas.updateUI();
            }
            for(Mascota mas : listadomascotas){
                if(reg % 2 == 0) {
                    posX = 815;
                } else {
                    posX = 10;
                }
                crearPanelMascota(mas, true, posX, posY);
                if(reg >1 && reg % 2 == 0){
                        posY = posY + 135; 
                }
                reg++;
            }
        } else {
            JOptionPane.showMessageDialog(this.rootPane,"Debe ingresar al sistema para gestionar sus mascotas.","Mis mascotas",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnMisMascotasActionPerformed

    private void btnGestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuarioActionPerformed
        
        if(isLogged){
            GestionUsuario gestionUsuario = new GestionUsuario(sesion, sesion.getCusuario(), "EDITAR");
            gestionUsuario.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this.rootPane,"Debe ingresar al sistema para gestionar su usuario.","Usuario",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGestionarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
        
    }

    public void setSesion(Sesion sesion) {
        
        this.sesion = sesion;
        lblInicioBienvenida.setText("Bienvenido,");
        lblInicioNombre.setText(this.sesion.getNombreUsuario());
        final String avatar = "H".equals(this.sesion.getGenero()) ? "Hombre" : "Mujer";    
        lblInicioAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource(String.format("/images/img%s.png", avatar))));
        setDatosUsuario();
    }

    public boolean isIsLogged() {
        
        return isLogged;
    }

    public void setIsLogged(boolean isLogged) {
        
        this.isLogged = isLogged;
    }
    
    public void disableLogin(){
        
        btnInicioRegistrar.setEnabled(false);
        btnInicioLogin.setEnabled(false);
    }

    private void setDatosUsuario(){
        
        lblInicio.setText("Inicio de Sesión:");
        lblInicioSesion.setText(sesion.getFinicio());
        lblInfoSistema.setText(sesion.getSistema());   
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionarUsuario;
    private javax.swing.JButton btnInicioLogin;
    private javax.swing.JButton btnInicioRegistrar;
    private javax.swing.JButton btnInicioSalir;
    private javax.swing.JButton btnMisAdopciones;
    private javax.swing.JButton btnMisMascotas;
    private javax.swing.JButton btnPublicarMascota;
    private javax.swing.JButton btnVerMascotas;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFotoPortadaA;
    private javax.swing.JLabel lblFotoPortadaB;
    private javax.swing.JLabel lblFotoPortadaC;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIncioUtpl;
    private javax.swing.JLabel lblInfoSistema;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblInicioAutores;
    private javax.swing.JLabel lblInicioAvatar;
    private javax.swing.JLabel lblInicioBienvenida;
    private javax.swing.JLabel lblInicioNombre;
    private javax.swing.JLabel lblInicioPortada;
    private javax.swing.JLabel lblInicioSesion;
    private javax.swing.JLabel lblInicioSubtitulo;
    private javax.swing.JLabel lblInicioTitulo;
    private javax.swing.JLabel lblInicioTituloIntro;
    private javax.swing.JLabel lblInicioUniversidad;
    private javax.swing.JLabel lblLogoPrincipal;
    private javax.swing.JPanel panInicioInferior;
    private javax.swing.JPanel panInicioIntro;
    private javax.swing.JPanel panInicioLateral;
    private javax.swing.JPanel panInicioListadoMascotas;
    private javax.swing.JPanel panInicioSuperior;
    private javax.swing.JScrollPane scrInicioIntro;
    private javax.swing.JScrollPane scrInicioMascotas;
    private javax.swing.JTextPane txpInicioIntro;
    // End of variables declaration//GEN-END:variables
}
