package ec.edu.utpl.adopcionmascotas.vista;

import ec.edu.utpl.adopcionmascotas.controlador.ControladorLogin;
import ec.edu.utpl.adopcionmascotas.controlador.Validacion;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.ColorUIResource;


/**
 * Interfaz de Login de la aplicacion
 * 
 * @author Grupo 3 - Ingeniería de Software
 * @version 1.0
 */
public class Login extends javax.swing.JFrame {

    private ControladorLogin login;
    private Validacion validacion;
    private Integer cpregunta;
    
    /**
     * Constructor
     */
    public Login() {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            javax.swing.UIManager.put("OptionPane.background",new ColorUIResource(41,41,41));
            javax.swing.UIManager.put("Panel.background",new ColorUIResource(41,41,41));
            javax.swing.UIManager.put("OptionPane.messageForeground",new ColorUIResource(255,255,255));
            javax.swing.UIManager.put("Panel.background",new ColorUIResource(41,41,41));
            
            initComponents();
            setLocationRelativeTo(null);
            this.cpregunta = (int) (Math.random()*4)+1;
            this.validacion = new Validacion();
            this.login = new ControladorLogin(); 
            this.lblPregunta.setText(login.getPregunta(cpregunta));
        }catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e){
            javax.swing.JOptionPane.showMessageDialog(this.rootPane,"Imposible modificar el tema visual","Lookandfeel inválido.",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panLogin = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblPregunta = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        txtRespuesta = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblOlvidoCon = new javax.swing.JLabel();
        lblLogoOracle = new javax.swing.JLabel();
        panLoginLogo = new javax.swing.JPanel();
        lblLogoUtpl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(1000, 460));
        setMinimumSize(new java.awt.Dimension(1000, 460));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panLogin.setBackground(new java.awt.Color(41, 41, 41));
        panLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panLogin.setMinimumSize(new java.awt.Dimension(1000, 460));
        panLogin.setPreferredSize(new java.awt.Dimension(1000, 460));
        panLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario:");
        panLogin.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 145, 80, 25));

        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setToolTipText("Nombre de usuario.");
        panLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 145, 210, 25));

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Contraseña:");
        panLogin.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 80, 25));

        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setToolTipText("Contraseña del usuario.");
        panLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, 25));

        lblPregunta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPregunta.setForeground(new java.awt.Color(255, 255, 255));
        panLogin.add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 235, 300, 25));

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgRefrescar.png"))); // NOI18N
        btnRefresh.setToolTipText("Cambiar Pregunta de Seguridad");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.setOpaque(false);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        panLogin.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 235, 25, 25));
        btnRefresh.getAccessibleContext().setAccessibleName("btnRefresh");

        txtRespuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRespuesta.setToolTipText("Respuesta a la pregunta de seguridad.");
        panLogin.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 265, 300, 25));

        btnAceptar.setText("Entrar");
        btnAceptar.setToolTipText("Loguearse en el sistema.");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        panLogin.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 315, 70, 20));

        btnCancelar.setText("Salir");
        btnCancelar.setToolTipText("Volver a la pantalla principal.");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panLogin.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 315, 70, 20));

        lblOlvidoCon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblOlvidoCon.setForeground(new java.awt.Color(255, 255, 255));
        lblOlvidoCon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOlvidoCon.setText("¿Olvidó su contraseña?");
        lblOlvidoCon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOlvidoCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkRecuperacion(evt);
            }
        });
        panLogin.add(lblOlvidoCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 345, 150, -1));

        lblLogoOracle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoOracle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgLogoOracle.png"))); // NOI18N
        panLogin.add(lblLogoOracle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 150, 30));

        getContentPane().add(panLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 460));

        panLoginLogo.setBackground(new java.awt.Color(255, 54, 54));
        panLoginLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoUtpl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLogoUtpl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgLogoPrincipal.png"))); // NOI18N
        panLoginLogo.add(lblLogoUtpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 245, 150));

        getContentPane().add(panLoginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        try {
            String user = this.txtUsuario.getText().toLowerCase();
            char clave[] = this.txtPassword.getPassword();
            String password = new String(clave); 
            String respuesta = this.txtRespuesta.getText().toUpperCase();
            if(validacion.validarCamposVacios(user, password, respuesta)) {
                if(login.existeUsuario(user, this.cpregunta)){
                    if(login.validarRespuesta(respuesta)){
                        
                        if(login.loginUsuario(password)){
                            System.out.println(">>LOGIN:" + login.cusuario + " - " + user);
                            Bienvenida mensaje = new Bienvenida(login.cusuario, user);
                            mensaje.setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(this.rootPane,"La contraseña ingresada no es válida","Ingreso al Sistema",JOptionPane.WARNING_MESSAGE);
                            txtPassword.setText("");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this.rootPane,"La respuesta a la pregunta de seguridad no es correcta","Ingreso al Sistema",JOptionPane.WARNING_MESSAGE);
                    }                  
                } else {
                    JOptionPane.showMessageDialog(this.rootPane,"El usuario [" + user + "] no existe en el sistema","Ingreso al Sistema",JOptionPane.WARNING_MESSAGE);
                    txtPassword.setText("");
                }    
            } else {
                JOptionPane.showMessageDialog(this.rootPane,"Los campos Usuario, Contraseña y Respuesta son obligatorios","Ingreso al Sistema",JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void linkRecuperacion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkRecuperacion
        
        RecuperacionLogin recuperacion = new RecuperacionLogin(this.txtUsuario.getText());
        recuperacion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_linkRecuperacion

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        
        this.cpregunta = (int) (Math.random()*4)+1;
        this.lblPregunta.setText(login.getPregunta(cpregunta));
    }//GEN-LAST:event_btnRefreshActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel lblLogoOracle;
    private javax.swing.JLabel lblLogoUtpl;
    private javax.swing.JLabel lblOlvidoCon;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panLogin;
    private javax.swing.JPanel panLoginLogo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
