package ec.edu.utpl.adopcionmascotas.vista;

import ec.edu.utpl.adopcionmascotas.controlador.ControladorRecuperacion;
import ec.edu.utpl.adopcionmascotas.controlador.Validacion;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.ColorUIResource;


/**
 * Interfaz de Login de la aplicacion
 * 
 * @author Grupo 3 - Ingeniería de Software
 * @version 1.0
 */
public class RecuperacionLogin extends javax.swing.JFrame {

    private ControladorRecuperacion recuperacion;
    private Validacion validacion;
    private String usuario;
    private Integer pregunta;
    /**
     * Creates new form RecuperacionLogin
     */
    public RecuperacionLogin(String user) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            javax.swing.UIManager.put("OptionPane.background",new ColorUIResource(41,41,41));
            javax.swing.UIManager.put("Panel.background",new ColorUIResource(41,41,41));
            javax.swing.UIManager.put("OptionPane.messageForeground",new ColorUIResource(255,255,255));
            javax.swing.UIManager.put("Panel.background",new ColorUIResource(41,41,41));
            /*
            
            */
            initComponents();
            setLocationRelativeTo(null);
            
            if(user != null && !"".equals(user)){
                this.usuario = user;
                this.txtUsuarioRec.setText(user);
                this.txtUsuarioRec.setEnabled(false);
            } else {
                this.usuario = this.txtUsuarioRec.getText();
            }
            
            pregunta = (int) (Math.random()*4)+1;
            this.validacion = new Validacion();
            this.recuperacion = new ControladorRecuperacion(pregunta); 
            this.lblPreguntaRec.setText(recuperacion.getPregunta());
        }catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e){
            javax.swing.JOptionPane.showMessageDialog(this.rootPane,"No se puede modificar el tema visual","Lookandfeel inválido.",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panRecuperacion = new javax.swing.JPanel();
        lblUsuarioRec = new javax.swing.JLabel();
        lblIdentificacionRec = new javax.swing.JLabel();
        lblPreguntaRec = new javax.swing.JLabel();
        lblPasswordRec = new javax.swing.JLabel();
        lblPasswordCon = new javax.swing.JLabel();
        txtUsuarioRec = new javax.swing.JTextField();
        txtIdentificacionRec = new javax.swing.JTextField();
        txtPreguntaSeg = new javax.swing.JTextField();
        txtPasswordRec = new javax.swing.JPasswordField();
        txtPasswordCon = new javax.swing.JPasswordField();
        panencabezadoRec = new javax.swing.JPanel();
        lblIconoUtpl = new javax.swing.JLabel();
        lblTituloRecuperacion1 = new javax.swing.JLabel();
        lblTituloRecuperacion = new javax.swing.JLabel();
        panTituloRec = new javax.swing.JPanel();
        lblSubtituloRecuperacion = new javax.swing.JLabel();
        panInferiorRec = new javax.swing.JPanel();
        btnCancelarRec = new javax.swing.JButton();
        btnAceptarRec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restablecer contraseña");
        setMinimumSize(new java.awt.Dimension(500, 460));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panRecuperacion.setBackground(new java.awt.Color(41, 41, 41));
        panRecuperacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panRecuperacion.setMinimumSize(new java.awt.Dimension(500, 460));
        panRecuperacion.setPreferredSize(new java.awt.Dimension(500, 460));
        panRecuperacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuarioRec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuarioRec.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioRec.setText("Usuario de Sistema:");
        panRecuperacion.add(lblUsuarioRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 65, 140, 25));

        lblIdentificacionRec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdentificacionRec.setForeground(new java.awt.Color(255, 255, 255));
        lblIdentificacionRec.setText("Por favor ingrese su Identificación:");
        panRecuperacion.add(lblIdentificacionRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 140, 25));

        lblPreguntaRec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPreguntaRec.setForeground(new java.awt.Color(255, 255, 255));
        panRecuperacion.add(lblPreguntaRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 155, 360, 25));

        lblPasswordRec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPasswordRec.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordRec.setText("Nueva Contraseña:");
        panRecuperacion.add(lblPasswordRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 140, 25));

        lblPasswordCon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPasswordCon.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordCon.setText("Confirme Nueva Contraseña:");
        panRecuperacion.add(lblPasswordCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 285, 140, 25));

        txtUsuarioRec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioRec.setToolTipText("Nombre de usuario");
        panRecuperacion.add(txtUsuarioRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 65, 210, 25));

        txtIdentificacionRec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdentificacionRec.setToolTipText("Número de Identificación");
        panRecuperacion.add(txtIdentificacionRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 210, 25));

        txtPreguntaSeg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPreguntaSeg.setToolTipText("Respuesta a la pregunta de Seguridad");
        panRecuperacion.add(txtPreguntaSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 185, 360, 25));

        txtPasswordRec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPasswordRec.setToolTipText("Nueva Contraseña");
        panRecuperacion.add(txtPasswordRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 210, 25));

        txtPasswordCon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPasswordCon.setToolTipText("Confirme Nueva Contraseña");
        panRecuperacion.add(txtPasswordCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 285, 210, 25));

        getContentPane().add(panRecuperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 500, 380));

        panencabezadoRec.setBackground(new java.awt.Color(41, 41, 41));
        panencabezadoRec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoUtpl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgLogoPequeño.png"))); // NOI18N
        panencabezadoRec.add(lblIconoUtpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 15, 94, 50));

        lblTituloRecuperacion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloRecuperacion1.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRecuperacion1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloRecuperacion1.setText("Sistema");
        panencabezadoRec.add(lblTituloRecuperacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 15, 300, 20));

        lblTituloRecuperacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloRecuperacion.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRecuperacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloRecuperacion.setText("Adopción de Mascotas");
        panencabezadoRec.add(lblTituloRecuperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 35, 300, 30));

        getContentPane().add(panencabezadoRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 80));
        panencabezadoRec.getAccessibleContext().setAccessibleParent(this);

        panTituloRec.setBackground(new java.awt.Color(255, 54, 54));
        panTituloRec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSubtituloRecuperacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblSubtituloRecuperacion.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtituloRecuperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtituloRecuperacion.setText("Restablecer Contraseña");
        lblSubtituloRecuperacion.setAlignmentX(0.5F);
        panTituloRec.add(lblSubtituloRecuperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 390, -1));

        getContentPane().add(panTituloRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 500, 40));

        panInferiorRec.setBackground(new java.awt.Color(255, 54, 54));
        panInferiorRec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelarRec.setText("Cancelar");
        btnCancelarRec.setToolTipText("Volver al Login");
        btnCancelarRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRecActionPerformed(evt);
            }
        });
        panInferiorRec.add(btnCancelarRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 100, 30));

        btnAceptarRec.setText("Recuperar");
        btnAceptarRec.setToolTipText("Recuperar la Contraseña");
        btnAceptarRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarRecActionPerformed(evt);
            }
        });
        panInferiorRec.add(btnAceptarRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 30));

        getContentPane().add(panInferiorRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 500, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarRecActionPerformed
        
        try {
            String identificacion = this.txtIdentificacionRec.getText();
            String respuesta = this.txtPreguntaSeg.getText();
            this.usuario = this.txtUsuarioRec.getText();
            char clave[] = txtPasswordRec.getPassword();
            char claveRec[] = txtPasswordCon.getPassword();
            String password = new String(clave); 
            String passwordConf = new String(claveRec);
            if(validacion.validarCamposVacios(usuario, identificacion, respuesta, password, passwordConf)) {
                if(recuperacion.existeUsuario(usuario)){
                    if(recuperacion.validarIdentificacion(identificacion)){
                        if(recuperacion.validarRespuesta(respuesta)){
                            if(password.equals(passwordConf)){
                                if(recuperacion.savePassword(password)){
                                    JOptionPane.showMessageDialog(this.rootPane,"La nueva contraseña se guardó correctamente.","Recuperación de Contraseña",JOptionPane.INFORMATION_MESSAGE);
                                    abrirLogin();
                                } else {
                                    JOptionPane.showMessageDialog(this.rootPane,"Error al guardar la Nueva Contraseña.","Recuperación de Contraseña",JOptionPane.ERROR_MESSAGE);
                                }   
                            } else {
                                JOptionPane.showMessageDialog(this.rootPane,"Las contraseñas ingresadas no coinciden.","Recuperación de Contraseña",JOptionPane.WARNING_MESSAGE);
                                txtPasswordRec.setText("");
                                txtPasswordCon.setText("");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this.rootPane,"La respuesta de la Pregunta de Seguridad es incorrecta.","Recuperación de Contraseña",JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this.rootPane,"El número de Identificación del usuario es incorrecta.","Recuperación de Contraseña",JOptionPane.WARNING_MESSAGE);
                    }   
                } else {
                    JOptionPane.showMessageDialog(this.rootPane,"El usuario [" + usuario + "] no existe en el sistema","Recuperación de Contraseña",JOptionPane.WARNING_MESSAGE);
                }    
            } else {
                JOptionPane.showMessageDialog(this.rootPane,"Existen campos obligatorios sin Ingresar","Recuperación de Contraseña",JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnAceptarRecActionPerformed

    private void btnCancelarRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRecActionPerformed

        abrirLogin();  
    }//GEN-LAST:event_btnCancelarRecActionPerformed

    private void abrirLogin(){
        
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarRec;
    private javax.swing.JButton btnCancelarRec;
    private javax.swing.JLabel lblIconoUtpl;
    private javax.swing.JLabel lblIdentificacionRec;
    private javax.swing.JLabel lblPasswordCon;
    private javax.swing.JLabel lblPasswordRec;
    private javax.swing.JLabel lblPreguntaRec;
    private javax.swing.JLabel lblSubtituloRecuperacion;
    private javax.swing.JLabel lblTituloRecuperacion;
    private javax.swing.JLabel lblTituloRecuperacion1;
    private javax.swing.JLabel lblUsuarioRec;
    private javax.swing.JPanel panInferiorRec;
    private javax.swing.JPanel panRecuperacion;
    private javax.swing.JPanel panTituloRec;
    private javax.swing.JPanel panencabezadoRec;
    private javax.swing.JTextField txtIdentificacionRec;
    private javax.swing.JPasswordField txtPasswordCon;
    private javax.swing.JPasswordField txtPasswordRec;
    private javax.swing.JTextField txtPreguntaSeg;
    private javax.swing.JTextField txtUsuarioRec;
    // End of variables declaration//GEN-END:variables
}
