/*==================================================================
Database name:  Database
DBMS name:      ORACLE Version 12c Express Edition
Created on:     12/01/2021
Created by:     Grupo 3 - Ingenieria de Software
/*==================================================================*/

spool DDL_PARAMETRIZACION_INICIAL.log

-- ====================================================
-- CREACION DEL USUARIO MASCOTAS
-- ====================================================
CREATE USER mascotas IDENTIFIED BY COREinsidei7;

GRANT CONNECT, RESOURCE TO mascotas;
GRANT CREATE ANY TABLE, RESOURCE TO mascotas;
GRANT SELECT ANY TABLE, RESOURCE TO mascotas;
GRANT INSERT ANY TABLE, RESOURCE TO mascotas;
GRANT ALTER ANY TABLE, RESOURCE TO mascotas;
GRANT ALTER ANY INDEX, RESOURCE TO mascotas;
GRANT CREATE VIEW TO mascotas;

ALTER USER mascotas IDENTIFIED BY COREinsidei7 ACCOUNT UNLOCK;
CONNECT mascotas/COREinsidei7;

-- USUARIOS
CREATE TABLE MASCOTAS.TUSUARIO 
    (CUSUARIO NUMBER(4,0),
    IDENTIFICACION VARCHAR2(16) NOT NULL,
    NOMBRES VARCHAR2(120) NOT NULL,
    APELLIDOS VARCHAR2(120) NOT NULL,
    USUARIO VARCHAR2(30) NOT NULL,
    PASSWORD VARCHAR2(120),
    ESTADO VARCHAR2(3),
    CORREO VARCHAR2(120),
    GENERO VARCHAR2(1),
    ACTIVO NUMBER(1,0));

ALTER TABLE MASCOTAS.TUSUARIO ADD CONSTRAINT PK_CUSUARIO PRIMARY KEY (CUSUARIO);    

COMMENT ON TABLE MASCOTAS.TUSUARIO IS 'Tabla de Usuarios';
COMMENT ON COLUMN MASCOTAS.TUSUARIO.CUSUARIO IS 'Codigo de usuario';
COMMENT ON COLUMN MASCOTAS.TUSUARIO.IDENTIFICACION IS 'Identificacion del usuario';
COMMENT ON COLUMN MASCOTAS.TUSUARIO.NOMBRES IS 'Nombres del usuario';
COMMENT ON COLUMN MASCOTAS.TUSUARIO.APELLIDOS IS 'Apellidos del usuario';
COMMENT ON COLUMN MASCOTAS.TUSUARIO.USUARIO IS 'Usuario de cuenta del sistema';
COMMENT ON COLUMN MASCOTAS.TUSUARIO.PASSWORD IS 'Password de cuenta del sistema';
COMMENT ON COLUMN MASCOTAS.TUSUARIO.ESTADO IS 'Estado del usuario ACT:ACTIVO BLQ:BLOQUEADO CER;CARRADO';
COMMENT ON COLUMN MASCOTAS.TUSUARIO.CORREO IS 'Correo institucional del usuario';
COMMENT ON COLUMN MASCOTAS.TUSUARIO.GENERO IS 'Genero del usuario - H:HOMBRE  M:MUJER';
COMMENT ON COLUMN MASCOTAS.TUSUARIO.ACTIVO IS 'Estado del usuario - 1:ACTIVO  0:INACTIVO';
 
 
-- PREGUNTAS
CREATE TABLE MASCOTAS.TPREGUNTA 
    (CPREGUNTA NUMBER(4,0),
    PREGUNTA VARCHAR2(100) NOT NULL,
    ACTIVO NUMBER(1,0));
    
ALTER TABLE MASCOTAS.TPREGUNTA ADD CONSTRAINT PK_CPREGUNTA PRIMARY KEY (CPREGUNTA);    

COMMENT ON TABLE MASCOTAS.TPREGUNTA IS 'Tabla de Preguntas de Seguridad';
COMMENT ON COLUMN MASCOTAS.TPREGUNTA.CPREGUNTA IS 'Codigo de pregunta';
COMMENT ON COLUMN MASCOTAS.TPREGUNTA.PREGUNTA IS 'Descripcion de la pregunta';
COMMENT ON COLUMN MASCOTAS.TPREGUNTA.ACTIVO IS 'Estado del usuario - 1:ACTIVO  0:INACTIVO';


-- ROLES
CREATE TABLE MASCOTAS.TROL 
    (CROL NUMBER(4,0),
     NOMBRE VARCHAR2(40) NOT NULL,
     DESCRIPCION  VARCHAR2(100) NOT NULL,
     ACTIVO NUMBER(1,0));

ALTER TABLE MASCOTAS.TROL ADD CONSTRAINT PK_CROL PRIMARY KEY (CROL); 

COMMENT ON TABLE MASCOTAS.TROL IS 'Tabla de Roles del sistema';
COMMENT ON COLUMN MASCOTAS.TROL.CROL IS 'Codigo de rol';
COMMENT ON COLUMN MASCOTAS.TROL.NOMBRE IS 'Nombre del rol';
COMMENT ON COLUMN MASCOTAS.TROL.DESCRIPCION IS 'Descripcion del rol';
COMMENT ON COLUMN MASCOTAS.TROL.ACTIVO IS 'Estado del rol - 1:ACTIVO  0:INACTIVO';

prompt Done.
spool
